# application.properties (??)
spring.application.name=myproject
server.address=0.0.0.0

# JPA ?? ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ?? ??? ?? (????? ????)
spring.web.resources.static-locations=classpath:/static/

spring:
jackson:
date-format: yyyy-MM-dd
time-zone: UTC